lane_boundary:
  left:
  - &id001
    x: 22.5
    y: 0.0
    z: 0.0
  - x: 22.07
    y: 4.39
    z: 0.0
  - x: 20.79
    y: 8.61
    z: 0.0
  - x: 18.71
    y: 12.5
    z: 0.0
  - x: 15.91
    y: 15.91
    z: 0.0
  - x: 12.5
    y: 18.71
    z: 0.0
  - x: 8.61
    y: 20.79
    z: 0.0
  - x: 4.39
    y: 22.07
    z: 0.0
  - x: 0.0
    y: 22.5
    z: 0.0
  - x: -4.39
    y: 22.07
    z: 0.0
  - x: -8.61
    y: 20.79
    z: 0.0
  - x: -12.5
    y: 18.71
    z: 0.0
  - x: -15.91
    y: 15.91
    z: 0.0
  - x: -18.71
    y: 12.5
    z: 0.0
  - x: -20.79
    y: 8.61
    z: 0.0
  - x: -22.07
    y: 4.39
    z: 0.0
  - x: -22.5
    y: 0.0
    z: 0.0
  - x: -22.07
    y: -4.39
    z: 0.0
  - x: -20.79
    y: -8.61
    z: 0.0
  - x: -18.71
    y: -12.5
    z: 0.0
  - x: -15.91
    y: -15.91
    z: 0.0
  - x: -12.5
    y: -18.71
    z: 0.0
  - x: -8.61
    y: -20.79
    z: 0.0
  - x: -4.39
    y: -22.07
    z: 0.0
  - x: -0.0
    y: -22.5
    z: 0.0
  - x: 4.39
    y: -22.07
    z: 0.0
  - x: 8.61
    y: -20.79
    z: 0.0
  - x: 12.5
    y: -18.71
    z: 0.0
  - x: 15.91
    y: -15.91
    z: 0.0
  - x: 18.71
    y: -12.5
    z: 0.0
  - x: 20.79
    y: -8.61
    z: 0.0
  - x: 22.07
    y: -4.39
    z: 0.0
  - *id001
  right:
  - &id002
    x: 17.5
    y: 0.0
    z: 0.0
  - x: 17.16
    y: 3.41
    z: 0.0
  - x: 16.17
    y: 6.7
    z: 0.0
  - x: 14.55
    y: 9.72
    z: 0.0
  - x: 12.37
    y: 12.37
    z: 0.0
  - x: 9.72
    y: 14.55
    z: 0.0
  - x: 6.7
    y: 16.17
    z: 0.0
  - x: 3.41
    y: 17.16
    z: 0.0
  - x: 0.0
    y: 17.5
    z: 0.0
  - x: -3.41
    y: 17.16
    z: 0.0
  - x: -6.7
    y: 16.17
    z: 0.0
  - x: -9.72
    y: 14.55
    z: 0.0
  - x: -12.37
    y: 12.37
    z: 0.0
  - x: -14.55
    y: 9.72
    z: 0.0
  - x: -16.17
    y: 6.7
    z: 0.0
  - x: -17.16
    y: 3.41
    z: 0.0
  - x: -17.5
    y: 0.0
    z: 0.0
  - x: -17.16
    y: -3.41
    z: 0.0
  - x: -16.17
    y: -6.7
    z: 0.0
  - x: -14.55
    y: -9.72
    z: 0.0
  - x: -12.37
    y: -12.37
    z: 0.0
  - x: -9.72
    y: -14.55
    z: 0.0
  - x: -6.7
    y: -16.17
    z: 0.0
  - x: -3.41
    y: -17.16
    z: 0.0
  - x: -0.0
    y: -17.5
    z: 0.0
  - x: 3.41
    y: -17.16
    z: 0.0
  - x: 6.7
    y: -16.17
    z: 0.0
  - x: 9.72
    y: -14.55
    z: 0.0
  - x: 12.37
    y: -12.37
    z: 0.0
  - x: 14.55
    y: -9.72
    z: 0.0
  - x: 16.17
    y: -6.7
    z: 0.0
  - x: 17.16
    y: -3.41
    z: 0.0
  - *id002
entities:
- x: 15.5
  y: 0.0
  z: 1.0
  gamma: 3.14159
- x: -7.75
  y: 13.42
  z: 1.0
  gamma: 5.23599
- x: -7.75
  y: -13.42
  z: 1.0
  gamma: 7.33038
car_pos:
  x: 20.0
  y: 0.0
  z: 0.0
  gamma: 3.141592653589793
