lane_boundary:
  left:
  - x: 37.5
    y: 0.0
    z: 0.0
  - x: 36.78
    y: 7.32
    z: 0.0
  - x: 34.65
    y: 14.35
    z: 0.0
  - x: 31.18
    y: 20.83
    z: 0.0
  - x: 26.52
    y: 26.52
    z: 0.0
  - x: 20.83
    y: 31.18
    z: 0.0
  - x: 14.35
    y: 34.65
    z: 0.0
  - x: 7.32
    y: 36.78
    z: 0.0
  - x: 0.0
    y: 37.5
    z: 0.0
  - x: -7.32
    y: 36.78
    z: 0.0
  - x: -14.35
    y: 34.65
    z: 0.0
  - x: -20.83
    y: 31.18
    z: 0.0
  - x: -26.52
    y: 26.52
    z: 0.0
  - x: -31.18
    y: 20.83
    z: 0.0
  - x: -34.65
    y: 14.35
    z: 0.0
  - x: -36.78
    y: 7.32
    z: 0.0
  - x: -37.5
    y: 0.0
    z: 0.0
  - x: -36.78
    y: -7.32
    z: 0.0
  - x: -34.65
    y: -14.35
    z: 0.0
  - x: -31.18
    y: -20.83
    z: 0.0
  - x: -26.52
    y: -26.52
    z: 0.0
  - x: -20.83
    y: -31.18
    z: 0.0
  - x: -14.35
    y: -34.65
    z: 0.0
  - x: -7.32
    y: -36.78
    z: 0.0
  - x: -0.0
    y: -37.5
    z: 0.0
  - x: 7.32
    y: -36.78
    z: 0.0
  - x: 14.35
    y: -34.65
    z: 0.0
  - x: 20.83
    y: -31.18
    z: 0.0
  - x: 26.52
    y: -26.52
    z: 0.0
  - x: 31.18
    y: -20.83
    z: 0.0
  - x: 34.65
    y: -14.35
    z: 0.0
  - x: 36.78
    y: -7.32
    z: 0.0
  right:
  - x: 42.5
    y: 0.0
    z: 0.0
  - x: 41.68
    y: 8.29
    z: 0.0
  - x: 39.26
    y: 16.26
    z: 0.0
  - x: 35.34
    y: 23.61
    z: 0.0
  - x: 30.05
    y: 30.05
    z: 0.0
  - x: 23.61
    y: 35.34
    z: 0.0
  - x: 16.26
    y: 39.26
    z: 0.0
  - x: 8.29
    y: 41.68
    z: 0.0
  - x: 0.0
    y: 42.5
    z: 0.0
  - x: -8.29
    y: 41.68
    z: 0.0
  - x: -16.26
    y: 39.26
    z: 0.0
  - x: -23.61
    y: 35.34
    z: 0.0
  - x: -30.05
    y: 30.05
    z: 0.0
  - x: -35.34
    y: 23.61
    z: 0.0
  - x: -39.26
    y: 16.26
    z: 0.0
  - x: -41.68
    y: 8.29
    z: 0.0
  - x: -42.5
    y: 0.0
    z: 0.0
  - x: -41.68
    y: -8.29
    z: 0.0
  - x: -39.26
    y: -16.26
    z: 0.0
  - x: -35.34
    y: -23.61
    z: 0.0
  - x: -30.05
    y: -30.05
    z: 0.0
  - x: -23.61
    y: -35.34
    z: 0.0
  - x: -16.26
    y: -39.26
    z: 0.0
  - x: -8.29
    y: -41.68
    z: 0.0
  - x: -0.0
    y: -42.5
    z: 0.0
  - x: 8.29
    y: -41.68
    z: 0.0
  - x: 16.26
    y: -39.26
    z: 0.0
  - x: 23.61
    y: -35.34
    z: 0.0
  - x: 30.05
    y: -30.05
    z: 0.0
  - x: 35.34
    y: -23.61
    z: 0.0
  - x: 39.26
    y: -16.26
    z: 0.0
  - x: 41.68
    y: -8.29
    z: 0.0
entities:
- x: 43.5
  y: 0.0
  z: 1.0
  gamma: 3.14159
- x: -21.75
  y: 37.67
  z: 1.0
  gamma: 5.23599
- x: -21.75
  y: -37.67
  z: 1.0
  gamma: 7.33038
car_pos:
  x: 40.0
  y: 0.0
  z: 0.0
  gamma: 1.5707963267948966
